[FIXED JENKINS-21756] Decouple this from git plugin
... so that this plugin won't pick up jgit from git-client plugin.

git-client plugin updates its jgit plugin at its own pace, and if that
gets inconsistent with the jgit version git-server plugin uses, lots of
LinkageErrors and NoClassDefFoundError ensues.

Either we need to keep those two copies independent like this, or we
should just bundle jgit HTTP server jar into the base git-client plugin.

It only adds like 90KB on top of jgit core that's already 1.9MB, so it's
quite feasible